spring:
  profiles:
    active: local
  mvc:
    log-request-details: true
logging:
  level:
    reactor.netty.http.client.HttpClient: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

server:
  port: 8080
---
spring:
  profiles: local
rx:
  http:
    one-base-url: https://test-api.vip56.cn
    one-scheme: https
    one-host: test-api.vip56.cn
    one-port: -1
    two-base-url: http://localhost:8888
    two-scheme: http
    two-host: localhost
    two-port: 8888

---
spring:
  profiles: dev
server:
  port: 80

---
spring:
  profiles: test
server:
  port: 8088

---
spring:
  profiles: prod
server:
  port: 80